#!/usr/bin/env bash
set -euo pipefail

COMMAND="${1:-update}"
LOCAL_HOST=$(hostname)
TARGET="${2:-$LOCAL_HOST}"
SCRIPT_PATH="${BASH_SOURCE[0]}"

while [[ -L "$SCRIPT_PATH" ]]; do
  SCRIPT_DIR="$(cd -P "$(dirname "$SCRIPT_PATH")" && pwd)"
  SCRIPT_PATH="$(readlink "$SCRIPT_PATH")"

  [[ "$SCRIPT_PATH" != /* ]] && SCRIPT_PATH="$SCRIPT_DIR/$SCRIPT_PATH"
done

REPO_DIR="$(cd -P "$(dirname "$SCRIPT_PATH")" && pwd)"

OS="$(uname -s | tr '[:upper:]' '[:lower:]')"

log() {
  printf '[dotfiles] %s\n' "$*" >&2
}

abort() {
  printf '[dotfiles] ERROR: %s\n' "$*" >&2
  exit 1
}

has() {
  command -v "$1" >/dev/null 2>&1
}

ensure_nix() {
  if command -v nix >/dev/null 2>&1; then
    return
  fi

  log "Installing Nix..."
  sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --daemon
}

darwin() {
  local casks=(
    ghostty
  )

  log "Updating Homebrew..."
  brew update

  log "Installing casks: ${casks[*]}"

  brew install --cask "${casks[@]}"

  ensure_nix

  log "Installing nix packages"
  nix profile add "$REPO_DIR/nix" --extra-experimental-features 'nix-command flakes'
}

nixos() {
  log "Rebuilding NixOS configuration for $TARGET..."

  local flake="$REPO_DIR/nix#$TARGET"

  case "$LOCAL_HOST:$TARGET" in
    desktop:desktop)
      sudo nixos-rebuild switch --flake "$flake"
      ;;

    desktop:pi)
      nixos-rebuild switch --flake "$flake" --target-host casey@pi.local --sudo 
      ;;

    pi:*)
      sudo nixos-rebuild switch --flake "$flake" --build-host casey@desktop.local
      ;;

    *)
      abort "Unsupported rebuild path: local=$LOCAL_HOST target=$TARGET"
      ;;
  esac
}

build() {
  case "$OS" in
    darwin) darwin ;;
    linux) nixos ;;
    *) abort "Unsupported OS: $OS" ;;
  esac
}

update() {
  case "$OS" in
    linux)
      log "Updating NixOS flake..."
      nix flake update --flake "$REPO_DIR/nix"

      nixos
      ;;
    *)
      has topgrade || abort "topgrade is not installed."
      topgrade
      ;;
  esac

  log "Update complete."
}

case "$COMMAND" in
  build) build ;;
  update) update ;;
  *) abort "Usage: $0 [build|update]" ;;
esac

